###
POST http://localhost:8080/api/message
Content-Type: application/json
X-Idempotency-Key: KEY-123

{
  "text": "hello world"
}

###
POST http://localhost:8080/api/message
Content-Type: application/json
X-Idempotency-Key: KEY-2

{
  "text": " FAIL_ME"
}

###
